-- Parse JSON from nested web event data
-- Extracts key page view attributes for performance and user interaction analysis

SELECT
  id AS view_id,
  json_extract_path_text(application, 'name', TRUE) AS application_name,
  json_extract_path_text(application, 'id', TRUE) AS application_id,
  json_extract_path_text(browser, 'name', TRUE) AS browser_name,
  json_extract_path_text(context, 'page', TRUE) AS page_view,
  json_extract_path_text(context, 'citation_id', TRUE) AS citation_id,
  json_extract_path_text(device, 'name', TRUE) AS device_name,
  json_extract_path_text(device, 'type', TRUE) AS device_type,
  json_extract_path_text(geo, 'as', 'name', TRUE) AS service_provider,
  json_extract_path_text(geo, 'city', TRUE) AS ip_city,
  json_extract_path_text(geo, 'country_subdivision', TRUE) AS ip_state_province,
  json_extract_path_text(os, 'name', TRUE) AS os_name,
  json_extract_path_text(privacy, 'replay_name', TRUE) AS replay_name,
  service,
  json_extract_path_text(session, 'id', TRUE) AS session_id,
  json_extract_path_text(session, 'matching_retention', 'plan', TRUE) AS session_plan,
  json_extract_path_text(usr, 'user_type', TRUE) AS user_type,
  json_extract_path_text(usr, 'id', TRUE) AS user_id,
  json_extract_path_text(usr, 'email', TRUE) AS user_email,
  json_extract_path_text(usr, 'name', TRUE) AS user_name,
  etl_deleted_flag,
  json_extract_path_text(view, 'first_input_delay', TRUE) AS first_input_delay,
  json_extract_path_text(view, 'load_event', TRUE) AS load_event,
  json_extract_path_text(view, 'long_task', 'count', TRUE) AS long_task_count,
  json_extract_path_text(view, 'cumulative_layout_shift', TRUE) AS cumulative_layout_shift,
  json_extract_path_text(view, 'error', 'count', TRUE) AS error_count,
  json_extract_path_text(view, 'dom_content_loaded', TRUE) AS dom_content_loaded,
  json_extract_path_text(view, 'time_spent', TRUE) AS time_spent,
  json_extract_path_text(view, 'first_input_time', TRUE) AS first_input_time,
  json_extract_path_text(view, 'url_path_group', TRUE) AS url_path_group,
  json_extract_path_text(view, 'loading_time', TRUE) AS loading_time,
  json_extract_path_text(view, 'action', 'count', TRUE) AS action_count,
  json_extract_path_text(view, 'url_host', TRUE) AS url_host,
  json_extract_path_text(view, 'resource', 'count', TRUE) AS resource_count,
  json_extract_path_text(view, 'frustration', 'count', TRUE) AS frustration_count,
  json_extract_path_text(view, 'url', TRUE) AS url_view,
  json_extract_path_text(view, 'referrer', TRUE) AS referrer,
  etl_update_ts,
  timestamp
FROM
  your_schema.your_event_table;
